<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP9dziJq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP9dziJq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP9dziJq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP9dziJq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerP9dziJq\App_KernelDevDebugContainer([
    'container.build_hash' => 'P9dziJq',
    'container.build_id' => '3afa1185',
    'container.build_time' => 1697288332,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP9dziJq');
