<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSRfv32W\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSRfv32W/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSRfv32W.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSRfv32W\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSRfv32W\App_KernelDevDebugContainer([
    'container.build_hash' => 'SRfv32W',
    'container.build_id' => '65f5c526',
    'container.build_time' => 1697576848,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSRfv32W');
